package ui;

import com.sun.org.apache.bcel.internal.classfile.Code;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;

public class CodeForm {

    private final String welcomInput = "На данный номер телефона было отправлено\n" +
            "SMS - сообщение с кодом подтверждения.\n" +
            "Пожалуйства, введите этот код в поле ниже:";

    private JPanel rootPanel;
    private MainPanel mainPanel;
    private BigButton btnNext;
    private CodeInput txtCode;
    private WelcomPane panePhone;
    private WelcomPane paneWelcom;
    private IconPanel textFieldIcon;
    private EditPanel editPanel;


    private ChangePanel changePanel;

    private void createUIComponents() {
        // TODO: place custom component creation code here
        mainPanel = new MainPanel(MainPanel.MINI);
        panePhone = new WelcomPane(new Dimension(380, 60), "");
        paneWelcom = new WelcomPane(new Dimension(380, 80), welcomInput);
        txtCode = new CodeInput();
        btnNext = new BigButton("ПРОДОЛЖИТЬ");
        textFieldIcon = new IconPanel(IconPanel.ICON_LOCK);
        editPanel = new EditPanel(CodeInput.WIDTH + IconPanel.WIDTH);
    }

    public CodeForm() {

        $$$setupUI$$$();
        createUIComponents();
        panePhone.setFontSize(40.0F);
        paneWelcom.setFontSize(16.0F);
        mainPanel.addComponent(panePhone, 180);
        mainPanel.addComponent(paneWelcom, 25);
        editPanel.addIcon(textFieldIcon);
        editPanel.addTextField(txtCode);
        mainPanel.addComponent(editPanel, 10);
        mainPanel.addComponent(btnNext, 35);
        rootPanel.add(mainPanel, BorderLayout.CENTER);

        btnNext.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (changePanel != null) {
                    changePanel.next(txtCode.getPassword().toString());
                }
            }
        });
    }

    public void setPhoneNumber(String number) {
        panePhone.setText(number);
    }

    public JPanel getRootPanel() {
        return rootPanel;
    }

    public void setChangePanel(ChangePanel changePanel) {
        this.changePanel = changePanel;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new BorderLayout(0, 0));
        rootPanel.setMaximumSize(new Dimension(905, 596));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }


}
