package ui;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class ControlPanel {
    private JPanel rootPanel;
    private JButton btnDown;
    private JButton btnClose;

    public ControlPanel() {
        $$$setupUI$$$();
        btnClose.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Container frame = btnClose.getParent();
                do
                    frame = frame.getParent();
                while (!(frame instanceof JFrame));
                ((JFrame) frame).dispose();

            }
        });
        btnDown.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Container frame = btnDown.getParent();
                do
                    frame = frame.getParent();
                while (!(frame instanceof JFrame));
                ((JFrame) frame).setState(JFrame.ICONIFIED);
            }
        });
    }

    public JPanel getRootPanel() {
        return rootPanel;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        rootPanel = new JPanel();
        rootPanel.setLayout(new FlowLayout(FlowLayout.RIGHT, 10, 8));
        rootPanel.setBackground(new Color(-1579033));
        rootPanel.setEnabled(false);
        rootPanel.setMaximumSize(new Dimension(905, 35));
        rootPanel.setMinimumSize(new Dimension(905, 35));
        rootPanel.setPreferredSize(new Dimension(905, 35));
        btnDown.setMaximumSize(new Dimension(18, 18));
        btnDown.setMinimumSize(new Dimension(18, 18));
        btnDown.setOpaque(false);
        btnDown.setPreferredSize(new Dimension(18, 18));
        btnDown.setText("");
        rootPanel.add(btnDown);
        btnClose.setMaximumSize(new Dimension(18, 18));
        btnClose.setMinimumSize(new Dimension(18, 18));
        btnClose.setOpaque(false);
        btnClose.setPreferredSize(new Dimension(18, 18));
        btnClose.setText("");
        rootPanel.add(btnClose);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        btnDown = new ControlButton(ControlButton.BTN_TYPE.HIDE);
        btnClose = new ControlButton(ControlButton.BTN_TYPE.CLOSE);
    }
}
