package ui;

import core.Contact;
import core.UserProfile;
import main.UIResources;

import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.border.Border;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

public class EditContactForm {

    private final String editContact = "Редактирование контакта";
    private JPanel rootPanel;
    private BlackPanel blackPanel;
    private BottomBlackPanel bottomBlackPanel;
    private TextPane editContactPane;
    private TextPane phonePane;
    private DeleteButton btnDel;
    private BigButton btnSave;
    private FullNamePanel pnlFullName;
    private JPanel pnlContainer;
    private Contact contact;

    public EditContactForm(Contact contact) {
        this.contact = contact;
        createUIComponents();
        editContactPane.setForeground(UIResources.LIGHT_BLUE_COLOR);
        editContactPane.setFontSize(42.0F);
        phonePane.setForeground(Color.WHITE);
        phonePane.setFontSize(18.0F);
        pnlContainer.setOpaque(false);
        pnlContainer.setMaximumSize(new Dimension(550, 50));
        pnlContainer.setMinimumSize(new Dimension(550, 50));
        pnlContainer.setPreferredSize(new Dimension(550, 50));
       // pnlContainer.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.WHITE));
        pnlContainer.add(phonePane);
        pnlContainer.add(btnDel);
        blackPanel.addComponent(editContactPane, 110);
        blackPanel.addComponent(pnlFullName, 40);
        blackPanel.addComponent(pnlContainer, 20);
        blackPanel.addComponent(btnSave, 40);

        rootPanel.add(blackPanel, BorderLayout.CENTER);
        rootPanel.add(bottomBlackPanel, BorderLayout.SOUTH);
    }

    public JPanel getRootPanel() {
        return rootPanel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        blackPanel = new BlackPanel();
        bottomBlackPanel = new BottomBlackPanel();
        editContactPane = new TextPane(new Dimension(600, 50), editContact);
        phonePane = new TextPane(new Dimension(200, 30), contact.getPhone());
        btnDel = new DeleteButton();
        btnSave = new BigButton("СОХРАНИТЬ");
        pnlFullName = new FullNamePanel(contact.getName());
        pnlContainer = new JPanel(new FlowLayout(FlowLayout.CENTER));
    }

    private class DeleteButton extends JButton {
        private final String deleteUser = "удалить пользователя  ";
        private BufferedImage iconTrash;
        private final int height = 34;
        private final int width = 240;

        private Font font;

        public DeleteButton() {
            try {
                iconTrash = ImageIO.read(new File(UIResources.ICON_TRASH));
            } catch (IOException e) {
                e.printStackTrace();
            }

            setBackground(Color.BLACK);
            setHorizontalAlignment(JButton.RIGHT);
            font = UIResources.getFont(UIResources.OPEN_SANS_LIGHT);
            setFont(font.deriveFont(18.0F));
            setMaximumSize(new Dimension(width, height));
            setMinimumSize(new Dimension(width, height));
            setPreferredSize(new Dimension(width, height));
            setForeground(Color.RED);
            Border border = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.RED);
            setBorder(border);
            setText(deleteUser);
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            if (iconTrash != null) {
                g.drawImage(iconTrash, 10, 8, null);
            }
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new BorderLayout(0, 0));
        rootPanel.setMaximumSize(new Dimension(905, 630));
        rootPanel.setMinimumSize(new Dimension(905, 630));
        rootPanel.setPreferredSize(new Dimension(905, 630));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

}
