package ui;

import javax.swing.*;
import java.awt.*;

public class InputMessageForm {
    private JPanel rootPanel;
    private JPanel pnlTopGap;
    private JPanel pnlTime;
    private JPanel pnlRightGap;
    private JLabel lblTime;
    private JTextPane paneMessage;
    private JPanel pnlTimeGap;

    public JPanel getRootPanel() {
        return rootPanel;
    }

    public void setTextMessage(String text) {
        paneMessage.setText(text);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new BorderLayout(0, 0));
        rootPanel.setMaximumSize(new Dimension(2147483647, 48));
        rootPanel.setMinimumSize(new Dimension(80, 48));
        pnlTopGap = new JPanel();
        pnlTopGap.setLayout(new BorderLayout(0, 0));
        pnlTopGap.setPreferredSize(new Dimension(0, 10));
        rootPanel.add(pnlTopGap, BorderLayout.NORTH);
        pnlTime = new JPanel();
        pnlTime.setLayout(new BorderLayout(0, 0));
        pnlTime.setPreferredSize(new Dimension(0, 15));
        rootPanel.add(pnlTime, BorderLayout.SOUTH);
        pnlTimeGap = new JPanel();
        pnlTimeGap.setLayout(new BorderLayout(0, 0));
        pnlTimeGap.setMaximumSize(new Dimension(100, 2147483647));
        pnlTimeGap.setMinimumSize(new Dimension(100, 0));
        pnlTimeGap.setPreferredSize(new Dimension(100, 0));
        pnlTime.add(pnlTimeGap, BorderLayout.EAST);
        lblTime = new JLabel();
        Font lblTimeFont = this.$$$getFont$$$(null, -1, 9, lblTime.getFont());
        if (lblTimeFont != null) lblTime.setFont(lblTimeFont);
        lblTime.setHorizontalAlignment(4);
        lblTime.setRequestFocusEnabled(false);
        lblTime.setText("Вчера 21:40");
        pnlTime.add(lblTime, BorderLayout.CENTER);
        pnlRightGap = new JPanel();
        pnlRightGap.setLayout(new BorderLayout(0, 0));
        pnlRightGap.setPreferredSize(new Dimension(100, 0));
        rootPanel.add(pnlRightGap, BorderLayout.EAST);
        paneMessage = new JTextPane();
        paneMessage.setText("Какое-то сообщение..");
        rootPanel.add(paneMessage, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
