package ui;

import javax.swing.*;
import java.awt.*;

public class ListItemForm {
    private JPanel pnlItem;
    private JPanel pnlPhoto;
    private JPanel pnlRight;
    private JPanel pnlContact;
    private JTextPane paneName;
    private JTextPane paneLast;
    private JPanel rootPanel;

    public ListItemForm() {

    }

    public JPanel getRootPanel() {
        return rootPanel;
    }

    public void setName(String name) {
        paneName.setText(name);
    }

    public void setLast(String last) {
        paneLast.setText(last);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new BorderLayout(0, 0));
        rootPanel.setMaximumSize(new Dimension(250, 50));
        rootPanel.setPreferredSize(new Dimension(250, 40));
        pnlItem = new JPanel();
        pnlItem.setLayout(new BorderLayout(0, 0));
        pnlItem.setMaximumSize(new Dimension(250, 50));
        pnlItem.setMinimumSize(new Dimension(250, 50));
        pnlItem.setPreferredSize(new Dimension(250, 50));
        rootPanel.add(pnlItem, BorderLayout.CENTER);
        pnlPhoto = new JPanel();
        pnlPhoto.setLayout(new BorderLayout(0, 0));
        pnlPhoto.setAutoscrolls(true);
        pnlPhoto.setBackground(new Color(-2363905));
        pnlPhoto.setPreferredSize(new Dimension(50, 0));
        pnlItem.add(pnlPhoto, BorderLayout.WEST);
        pnlRight = new JPanel();
        pnlRight.setLayout(new BorderLayout(0, 0));
        pnlRight.setPreferredSize(new Dimension(5, 0));
        pnlItem.add(pnlRight, BorderLayout.EAST);
        pnlContact = new JPanel();
        pnlContact.setLayout(new BorderLayout(0, 0));
        pnlItem.add(pnlContact, BorderLayout.CENTER);
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$("Nakula", Font.PLAIN, 9, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setText("2 мин");
        pnlContact.add(label1, BorderLayout.EAST);
        paneName = new JTextPane();
        paneName.setText("Андрей Петров");
        pnlContact.add(paneName, BorderLayout.NORTH);
        paneLast = new JTextPane();
        paneLast.setPreferredSize(new Dimension(30, 23));
        paneLast.setText("Хорошо! До встречи ...");
        pnlContact.add(paneLast, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
