package ui;

import javax.swing.*;
import java.awt.*;

public class OutputMessageForm {
    private JPanel rootPanel;
    private JPanel pnlTopGap;
    private JPanel pnlTime;
    private JPanel pnlLeftGap;
    private JTextPane paneText;
    private JPanel pnlTimeGap;
    private JLabel lblTime;

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    public JPanel getRootPanel() {
        return rootPanel;
    }

    public void setTextMessage(String msg) {
        paneText.setText(msg);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new BorderLayout(0, 0));
        rootPanel.setInheritsPopupMenu(false);
        rootPanel.setMaximumSize(new Dimension(2147483647, 48));
        rootPanel.setMinimumSize(new Dimension(0, 48));
        rootPanel.setPreferredSize(new Dimension(0, 48));
        pnlTopGap = new JPanel();
        pnlTopGap.setLayout(new BorderLayout(0, 0));
        pnlTopGap.setMaximumSize(new Dimension(2147483647, 10));
        pnlTopGap.setMinimumSize(new Dimension(0, 10));
        pnlTopGap.setPreferredSize(new Dimension(0, 10));
        rootPanel.add(pnlTopGap, BorderLayout.NORTH);
        pnlTime = new JPanel();
        pnlTime.setLayout(new BorderLayout(0, 0));
        pnlTime.setMaximumSize(new Dimension(2147483647, 15));
        pnlTime.setMinimumSize(new Dimension(0, 15));
        pnlTime.setPreferredSize(new Dimension(0, 15));
        rootPanel.add(pnlTime, BorderLayout.SOUTH);
        pnlTimeGap = new JPanel();
        pnlTimeGap.setLayout(new BorderLayout(0, 0));
        pnlTimeGap.setMaximumSize(new Dimension(100, 2147483647));
        pnlTimeGap.setMinimumSize(new Dimension(100, 0));
        pnlTimeGap.setPreferredSize(new Dimension(100, 0));
        pnlTime.add(pnlTimeGap, BorderLayout.WEST);
        lblTime = new JLabel();
        lblTime.setFocusTraversalPolicyProvider(false);
        Font lblTimeFont = this.$$$getFont$$$(null, -1, 9, lblTime.getFont());
        if (lblTimeFont != null) lblTime.setFont(lblTimeFont);
        lblTime.setText("5 мин. назад");
        pnlTime.add(lblTime, BorderLayout.CENTER);
        pnlLeftGap = new JPanel();
        pnlLeftGap.setLayout(new BorderLayout(0, 0));
        pnlLeftGap.setMaximumSize(new Dimension(100, 2147483647));
        pnlLeftGap.setMinimumSize(new Dimension(100, 0));
        pnlLeftGap.setPreferredSize(new Dimension(100, 0));
        rootPanel.add(pnlLeftGap, BorderLayout.WEST);
        paneText = new JTextPane();
        rootPanel.add(paneText, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
