package ui;

import javax.swing.*;
import java.awt.*;

public class PhoneNumberFrom {

    private final String welcomInput = "Введите код страны и номер мобильного телефона";
    private JPanel rootPanel;
    private JPanel pnlMain;
    private JPanel pnlLogo;
    /**
     * private JPanel pnlMain;
     * private JTextPane txtWelcomInput;
     * private JTextField txtPhoneNumber;
     * private JButton btnNext;
     **/

    private ChangePanel changePanel;

    private void createUIComponents() {
        // TODO: place custom component creation code here
        pnlMain = new MainPanel();
        pnlLogo = new LogoPanel(LogoPanel.LARGE);
    }

    public PhoneNumberFrom() {

        /**pnlMain.setLayout(new BoxLayout(pnlMain, BoxLayout.Y_AXIS));
         btnNext.setBackground(new Color(21, 61, 242));
         txtWelcomInput.setText(welcomInput);

         btnNext.addActionListener(new ActionListener() {
        @Override public void actionPerformed(ActionEvent e) {
        if (changePanel != null) {
        changePanel.next(txtPhoneNumber.getText());
        }
        }
        });**/
    }

    public JPanel getRootPanel() {
        return rootPanel;
    }

    public void setChangePanel(ChangePanel changePanel) {
        this.changePanel = changePanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        rootPanel = new JPanel();
        rootPanel.setLayout(new BorderLayout(0, 0));
        pnlMain.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 40));
        pnlMain.setInheritsPopupMenu(false);
        pnlMain.setMaximumSize(new Dimension(905, 596));
        pnlMain.setMinimumSize(new Dimension(905, 596));
        pnlMain.setPreferredSize(new Dimension(905, 596));
        rootPanel.add(pnlMain, BorderLayout.CENTER);
        pnlLogo.setMaximumSize(new Dimension(165, 168));
        pnlLogo.setMinimumSize(new Dimension(165, 168));
        pnlLogo.setPreferredSize(new Dimension(165, 168));
        pnlMain.add(pnlLogo);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

}
