package ui;

import core.UserProfile;
import main.UIResources;

import javax.swing.*;
import javax.swing.border.Border;
import java.awt.*;

import static ui.BottomBlackPanel.HEIGHT;

public class ProfileForm {
    private JPanel rootPanel;
    private BlackPanel blackPanel;
    private BottomBlackPanel bottomBlackPanel;
    private ExitButton btnExit;
    private TextPane phonePane;
    private UserProfile userProfile;


    private void createUIComponents() {
        // TODO: place custom component creation code here
        blackPanel = new BlackPanel();
        bottomBlackPanel = new BottomBlackPanel();
        btnExit = new ExitButton();
        phonePane = new TextPane(new Dimension(100, 30), "+7999 212 55 49");
        phonePane.setForeground(Color.WHITE);
    }

    public ProfileForm(UserProfile uf) {
        this.userProfile = uf;
        createUIComponents();
        JPanel eastPanel = createEastPanel();
        eastPanel.add(btnExit);
        eastPanel.add(phonePane);
        bottomBlackPanel.addEastPanel(eastPanel);
        rootPanel.add(blackPanel, BorderLayout.CENTER);
        rootPanel.add(bottomBlackPanel, BorderLayout.SOUTH);
    }

    public JPanel getRootPanel() {
        return rootPanel;
    }

    private JPanel createEastPanel() {
        FlowLayout flowLayout = new FlowLayout(FlowLayout.RIGHT);
        Dimension bSize = btnExit.getPreferredSize();
        flowLayout.setHgap(40);
        flowLayout.setVgap((BottomBlackPanel.HEIGHT - bSize.height) / 2);
        JPanel panel = new JPanel(flowLayout);
        panel.setOpaque(false);
        panel.setPreferredSize(new Dimension(400, BottomBlackPanel.HEIGHT));
        panel.setMaximumSize(new Dimension(400, BottomBlackPanel.HEIGHT));
        panel.setMinimumSize(new Dimension(400, BottomBlackPanel.HEIGHT));
        return panel;
    }


    private class ExitButton extends JButton {

        private final String caption = "ВЫЙТИ";
        public ExitButton() {

            Border border = BorderFactory.createMatteBorder(0, 0, 1, 0, UIResources.LIGHT_BLUE_COLOR);
            setBorder(border);
            setForeground(UIResources.LIGHT_BLUE_COLOR);
            setBackground(Color.BLACK);
            Font font = UIResources.getFont(UIResources.OPEN_SANS_REGULAR);
            setFont(font.deriveFont(15.0f));
            FontMetrics fontMetrics = getFontMetrics(font.deriveFont(15.0f));
            Dimension size  = new Dimension(fontMetrics.stringWidth(caption), fontMetrics.getHeight());
            setMaximumSize(size);
            setMinimumSize(size);
            setPreferredSize(size);
            setText(caption);

        }



    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new BorderLayout(20, 0));
        rootPanel.setMaximumSize(new Dimension(905, 630));
        rootPanel.setMinimumSize(new Dimension(905, 630));
        rootPanel.setPreferredSize(new Dimension(905, 630));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

}
