package ui;

import javax.swing.*;
import java.awt.*;

public class RegistrationForm {

    private final String welcomInput = "Введите ваше имя и фамилию\nдля завершения регистрации";
    private JPanel rootPanel;

    private LogoPanel mainPanel;
    private BigButton btnClose;
    private TextPane paneWelcom;
    private TextInput txtFirstName;
    private TextInput txtLastName;


    private void createUIComponents() {
        // TODO: place custom component creation code here
        mainPanel = new LogoPanel(LogoPanel.MINI);
        paneWelcom = new TextPane(new Dimension(380, 60), welcomInput);
        txtFirstName = new TextInput(TextInput.NAME_INPUT, "Имя");
        txtLastName = new TextInput(TextInput.NAME_INPUT, "Фамилия");
        btnClose = new BigButton("ЗАВЕРШИТЬ");
    }

    public RegistrationForm() {
        createUIComponents();
        paneWelcom.setFontSize(16.0F);
        mainPanel.addComponent(paneWelcom, 180);
        mainPanel.addComponent(txtFirstName, 20);
        mainPanel.addComponent(txtLastName, 20);
        mainPanel.addComponent(btnClose, 55);
        rootPanel.add(mainPanel, BorderLayout.CENTER);
    }

    public JPanel getRootPanel() {
        return rootPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new BorderLayout(0, 0));
        rootPanel.setMaximumSize(new Dimension(905, 622));
        rootPanel.setMinimumSize(new Dimension(905, 622));
        rootPanel.setPreferredSize(new Dimension(905, 622));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
